apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-node-app-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ShamilRizwan/k8s
  ref:
    branch: main
  secretRef:
    name: git-secret  # Use the name of the secret containing Git credentials if required
